Mock email backend and create tests and verify error handling
majikode/django-nitro-mailer pull request #2
Opened 2024-09-10 07:50 UTC by majaszymajda

2024-09-10 11:57 UTC, exler requested changes
Dobry start :+1:

2024-09-10 11:57 UTC, exler commented on pytest.ini
> +[pytest]
Trzymajmy konfiguracje w `pyproject.toml`: https://docs.pytest.org/en/7.1.x/reference/customize.html#pyproject-toml

2024-09-10 11:57 UTC, exler commented on pyproject.toml
> +requests = "^2.31.0"
Chyba zostało po implementacji API backend ;)

2024-09-10 11:57 UTC, exler commented on manage.py
> +    "EMAIL_BACKEND_TYPE": "smtp",
Nazwijmy tą zmienną `NITRO_MAILER_EMAIL_BACKEND`, tak, żeby była unikalna dla naszej paczki.

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +    assert email_instance.priority == Email.Priorities.HIGH
Ten test raczej zbędny, bo to jest zwykłe pole, więc na pewno będzie działać (nie testujemy podstawowej funkcjonalności Django)

2024-09-10 11:57 UTC, exler commented on dev_settings.py
> +DEBUG = True
Skoro mamy ten plik, to z `manage.py` można usunąć te `DEFAULT_SETTINGS` i dać `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dev_settings.py")`

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/models.py
> +        app_label = 'django_nitro_mailer'
Co to daje?

2024-09-10 11:57 UTC, exler commented on conftest.py
> +        )
Chyba to wszystko możemy usunąć? Te settingsy powinny się konfigurować przez te default settings ustawione w pytest, a chcemy mieć w memory bazę danych.

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tasks.py
> +                print(f"Email instance: {email_instance}")
Nie używajmy `print` w produkcyjnym kodzie; tylko trzeba zrobić instancję loggera i logować z użyciem `logger.<log_level>`. W tym przypadku reprezentacja nic i tak nie da, więcej sugeruję usunąć całkiem, a poniżej `logger.exception`

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tasks.py
> +        queryset = Email.objects.filter(priority__gt=0).order_by("-priority", "created_at")
Sugeruję `Email.objects.exclude(priority=Email.Priorities.DEFERRED)` dla czytelności

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tasks.py
> +        for email in queryset:
Musimy tutaj użyć `queryset.select_for_update(nowait=True)`, żeby nie próbować blokować workerów, ale też nie pozwalać na wyścigi z wysyłką emaili.

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tasks.py
> +                email_instance = email.email
Zmieńmy `email` na `email_obj`, a `email_instance` na `email_message` dla lepszej czytelności.

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tasks.py
> +                    success = connection.send_messages([email_instance])
`connection.send_messages` zwraca (w teorii) ilość wysłanych wiadomości, ale w praktyce nie oznacza błędu. Więc nie zapisujmy jego zwrotki i polegajmy jedynie na wyjątkach.

2024-09-10 11:57 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +def test_send_emails_backend_error(mock_send_messages, mock_get_connection):
Typujmy też proszę parametry testów

2024-09-11 14:43 UTC, exler reviewed
Czekam jeszcze na `backend.py` i zmiany w testach

2024-09-11 14:43 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +    print(settings.DATABASES)
Bez printów w kodzie

2024-09-11 21:16 UTC, majaszymajda commented
nie wiem czy dobrze zrozumiałam to co powiedziałeś na koniec o funkcji  send_mass_mail, ale mam nadzieje, że tak 😅

2024-09-12 19:17 UTC, exler approved these changes

2024-09-12 19:17 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +def test_send_emails_with_priorities(mock_send_messages):
Nie ma typowania :smile:

2024-09-13 09:41 UTC, merged