MAJI-80 feat(logging): add logging for email success
majikode/django-nitro-mailer pull request #3
Opened 2024-09-19 09:03 UTC by majaszymajda

https://linear.app/majikode/issue/MAJI-80/logowanie-wysylki-wiadomosci

2024-09-19 10:13 UTC, exler requested changes

2024-09-19 10:13 UTC, exler commented on django_nitro_mailer/tasks.py
> +                    logger.info(str(email_log))
Myślę, że możemy tutaj zrobić troszkę ładniejszą wiadomość:
```suggestion
                    logger.info("Email sent successfully", extra={"recipients": email_obj.recipients, "created_at": timezone.now()})
```

2024-09-19 10:13 UTC, exler commented on django_nitro_mailer/tasks.py
> +                    email_log = EmailLog.objects.create(
To miało być tworzone zależnie od zmiennej środowiskowej

2024-09-20 09:24 UTC, exler commented on django_nitro_mailer/tasks.py
> +                    if email_logging_enabled:
Maja, miałaś zrobić ten warunek na logowanie w bazie, a nie zwykłe.

2024-09-20 15:26 UTC, exler commented
Maja, z całym szacunkiem, ale przeczytaj proszę jeszcze raz treść zadania. Są wypisane dwa case'y, jeden z logiem w bazie danych + zwykłym, drugi tylko ze zwykłym logowaniem. Naprawdę nie mógłbym być bardziej precyzyjny, ale chyba bez zastanowienia zaczęłaś pisać kod i muszę prosić o tę zmianę już trzeci raz.

2024-09-21 10:36 UTC, majaszymajda commented
Masz, racje przepraszam Cie bardzo, przeczytałam ten task i skupiłam się na tej części dotyczącej dodania samego logowania o wysyłce mailu i później nie wróciłam już do tego taska. A powinnam była po Twoim pierwszym komentarzu, bo wydawało mi się, że inny cel miało to zadanie. Jeszcze raz bardzo Cie przepraszam, już go poprawiam 😞

2024-09-22 12:56 UTC, exler approved these changes

2024-09-22 12:57 UTC, merged