MAJI-83 Possibility of sending emails synchronously
majikode/django-nitro-mailer pull request #6
Opened 2024-09-23 14:21 UTC by majaszymajda

Nie jestem przekonana do umiejscowienia tego w backend.py jak funkcjonalnie pokrywa się to z task.py ale z drugiej strony jest to drugi backend do wyboru, więc dałam go do tego pliku, ale nie jestem pewna jak powinno to być

2024-09-23 18:33 UTC, exler requested changes
Zmień nazwę `backend.py` na `backends.py`. I zrób proszę rebase, bo wciągnąłem Twoje zmiany z throttlowaniem.

2024-09-23 18:33 UTC, exler commented on django_nitro_mailer/backend.py
> +        return successful_sends
Potrzebowałbym, zrobiła funkcję `send_email_message`  która by przyjmowała pojedynczą wiadomość `EmailMessage` i robiła to, co robi teraz `send_emails`. Następnie wykorzystywała tę funkcję zarówno tu jak i tam.

2024-09-24 20:29 UTC, exler requested changes

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +    settings.NITRO_MAILER_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
Dopiero teraz to zauważyłem; nie powinnaś nadpisywać ustawień w ten sposób, bo jest szansa, że te settingsy "wyciekną" poza ten test. Powinnaś nadpisywać ustawienia nadpisująć fixture od `pytest-django`: https://docs.djangoproject.com/en/5.1/topics/testing/tools/#django.test.override_settings

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +    backend = SyncBackend()
Nie musisz tworzyć backendu, skoro ustawiasz `EMAIL_BACKEND`. Używaj `send_mail`, wtedy od razu testujesz czy backend jest dobrze skonfigurowany.

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +    assert EmailLog.objects.count() == 1
Sprawdź też czy na pewno to jest `EmailLog` z `result = failure`; `EmailLog.objects.filter(result=fail).count()`

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/tasks.py
> +            email_message = pickle.loads(email_obj.email_data)
Używajmy property `email_obj.email` w razie, gdyby sposób serializacji się zmienił.

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/tasks.py
> +def send_email_message(email_data: EmailMessage, connection) -> bool:
`connection` też możemy otypować :wink:

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/backends.py
> +    def get_connection(self, fail_silently=False):
Nawet jeśli samo Django nie definiuje typowania, to my je chcemy.

2024-09-24 20:29 UTC, exler commented on django_nitro_mailer/tasks.py
> +        if email_data:
I tutaj typowanie powinno Ci było pomóc, bo w `email_data` zawsze przyjmujesz `EmailMessage`, więc nie spodziewasz się, że `if email_data` kiedykolwiek nie będzie prawdziwe. Dlatego wynieś proszę stąd ten warunek i sprawdzaj to przed wywołaniem tej funkcji w `send_emails`.

2024-09-25 14:55 UTC, exler requested changes

2024-09-25 14:55 UTC, exler commented on django_nitro_mailer/tasks.py
> +                logger.error(f"Failed to send or delete email {email_obj.id}: {e}")
Używamy `extra` i `exc_info`

2024-09-25 14:55 UTC, exler commented on django_nitro_mailer/tasks.py
> +                if email_obj.email:
Ale chcemy zalogować też błąd w innym przypadku

2024-09-25 14:55 UTC, exler commented on django_nitro_mailer/tests/test_tasks.py
> +)
Jeśli to działa, to jestem pod wrażeniem, ale tutaj moja wina, bo wysłałem Ci zły link :sweat: Chodziło mi oczywiście o funkcję od pytest: https://pytest-django.readthedocs.io/en/latest/configuring_django.html#overriding-individual-settings

2024-09-25 14:57 UTC, majaszymajda commented on django_nitro_mailer/tests/test_tasks.py
> +)
na początku trochę zepsuło pare testów ale udało się je naprawić i działa 😅

2024-09-26 08:44 UTC, exler approved these changes

2024-09-26 08:44 UTC, merged